### ISSUE TITLE
Undefined GJSON

### ISSUE THREAD

**Issue by keep-learning-go** [tegk/WebBitcoinEscrow#1]
[Target OS - CentOS 7]
Hi there! In the process of doing:
`go get github.com/tegk/WebBitcoinEscrow` it pops this error:
```
# github.com/tegk/WebBitcoinEscrow
src/github.com/tegk/WebBitcoinEscrow/main.go:127:11: undefined: gjson
src/github.com/tegk/WebBitcoinEscrow/main.go:143:11: undefined: gjson
src/github.com/tegk/WebBitcoinEscrow/main.go:165:9: undefined: gjson
```
--
Can you please tell me, how can I resolve this?

**Comment by tegk** [comment]
Sorry, "github.com/tidwall/gjson" was not imported. 

go get -u github.com/tidwall/gjson

If you run in other problems just let me know.
