### ISSUE TITLE
BTC address won't show up.

### ISSUE THREAD

**Issue by keep-learning-go** [tegk/WebBitcoinEscrow#4]
Hey there, I've finally installed this project on my VPS but everytime I try to create an escrow it won't dosplay BTC address to send bitcoins. 
Also, I noticed, everytime I try to create new escrow Blockchain.com sends a verification email to allow "login", I visit link and verify as soon as I can but still never made it work. I've no idea what I can be doing wrong. Can you help please?
upd. I've made sure that blockchain service is up and running on my system, if its not - escrow displays following message: "`Error: Could not generate address.`". But in my case it loads normally but won't display BTC address.
![screen](https://user-images.githubusercontent.com/42155242/50540625-1f9a2200-0b8d-11e9-80c6-7e4b214d49cd.PNG)

**Comment by tegk** [comment]
I would belive that your blockchain.info account does not allow api Access.

**Comment by asheroto** [comment]
Hey there, this is happening for me as well.  I noticed an error - it can't find all.js or logo.png - returns a 404 error.
